categories:
  UzbecanoSite:
    label: 'Site Package'
  UzbecanoSite.pages:
    label: 'Pages'
    parent: UzbecanoSite

settings:
  uzbecanoSite.pages.footerMeta:
    label: 'Footer Meta Menu'
    category: UzbecanoSite.pages
    description: 'ID of the folder or page for the footer meta menu.'
    type: int
    default: 1
