base: 'https://uzbecano.ddev.site/'
dependencies:
  - uzbecano/uzbecano-site
  - uzbecano/telegram-messenger
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_GB.utf8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: ''
