name: Testing Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'testing'

concurrency:
  group: ${{ github.head_ref || github.workflow }}

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/testing' }}
    name: Deployment and continuous Integration
    uses: Leuchtfeuer/deployment-runner/.github/workflows/ci_deploy.yaml@v3.3
    with:
      stage: 'testing'
      phpVersion: '8.3'
      nodeVersion: '24'
      runner: ${{ vars.RUNNER }}
      anthropicModel: ${{ vars.ANTHROPIC_MODEL }}
      runPHPCodeStyle: false
      runPHPStan: false
      runTypoScriptLinter: true
      runXliffLinter: false
      runUnitTests: false
      runFunctionalTests: false
    secrets:
      PRIVATE_KEY: ${{ secrets.JENKINS_PRIVATE_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      KNOWN_HOSTS: ${{ vars.KNOWN_HOSTS }}
      KNOWN_HOSTS_COMMON: ${{ vars.KNOWN_HOSTS_COMMON }}
      SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
