name: Staging Deployment

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.workflow }}

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/staging' }}
    name: Deployment (Staging)
    uses: Leuchtfeuer/deployment-runner/.github/workflows/deploy.yaml@v3.3
    with:
      stage: 'staging'
      phpVersion: '8.3'
      nodeVersion: '24'
      runner: ${{ vars.RUNNER }}
    secrets:
      PRIVATE_KEY: ${{ secrets.JENKINS_PRIVATE_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      KNOWN_HOSTS: ${{ vars.KNOWN_HOSTS }}
      KNOWN_HOSTS_COMMON: ${{ vars.KNOWN_HOSTS_COMMON }}
      SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
